# THIS FILE ONLY EXISTS TO MAKE sql-migrate CLI HAPPY
development:
  dialect: postgres
  dir: azar-db/migrations
  datasource: postgres://${AZAR_DB_USER}:${AZAR_DB_PASS}@${AZAR_DB_HOST}:${AZAR_DB_PORT}/${AZAR_DB_NAME}?sslmode=disable