// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Policy struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Action      string           `json:"action"`
	Resource    string           `json:"resource"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Role struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type RolePolicy struct {
	RoleID   int32 `json:"role_id"`
	PolicyID int32 `json:"policy_id"`
}

type User struct {
	ID        int32            `json:"id"`
	Username  string           `json:"username"`
	Email     pgtype.Text      `json:"email"`
	FirstName pgtype.Text      `json:"first_name"`
	LastName  pgtype.Text      `json:"last_name"`
	GroupID   pgtype.Int4      `json:"group_id"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type UserGroup struct {
	ID        int32            `json:"id"`
	GroupName string           `json:"group_name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type UserGroupRoleMap struct {
	UserGroupID int32 `json:"user_group_id"`
	RoleID      int32 `json:"role_id"`
}

type UserRole struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}
