// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type OauthAccessToken struct {
	AccessToken string
	ClientID    string
	UserID      int32
	Expires     time.Time
	Scope       string
}

type OauthAuthCode struct {
	AuthCode    string
	ClientID    string
	UserID      int32
	RedirectUri string
	Expires     time.Time
	Scope       string
}

type OauthClient struct {
	ID           int32
	ClientID     string
	ClientSecret string
	RedirectUri  string
	GrantTypes   string
	Scope        string
	UserID       int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type OauthJwt struct {
	ClientID  string
	Subject   sql.NullString
	PublicKey sql.NullString
}

type OauthPublicKey struct {
	ClientID            string
	PublicKey           string
	PrivateKey          string
	EncryptionAlgorithm string
}

type OauthRefreshToken struct {
	RefreshToken string
	ClientID     string
	UserID       int32
	Expires      time.Time
	Scope        string
}

type OauthScope struct {
	Scope     string
	IsDefault sql.NullBool
}

type Permission struct {
	ID          int32
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PermissionGroup struct {
	ID        int32
	GroupName string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PermissionGroupMap struct {
	PermissionID      int32
	PermissionGroupID int32
}

type PermissionGroupUserGroupMap struct {
	PermissionGroupID int32
	UserGroupID       int32
}

type PermissionGroupUserMap struct {
	PermissionGroupID int32
	UserID            int32
}

type User struct {
	ID        int32
	Username  string
	Email     string
	FirstName string
	LastName  string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserGroup struct {
	ID        int32
	GroupName string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserGroupMap struct {
	UserID      int32
	UserGroupID int32
}
